# StatefulSet for mail core service
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mailman-core
  namespace: mail
  labels:
    app: mail-suit-service
spec:
  serviceName: mail-suit-service
  replicas: 1
  selector:
    matchLabels:
      app: mail-suit-service
  template:
    metadata:
      labels:
        app: mail-suit-service
    spec:
      containers:
        - name: mailman-core
          image: maxking/mailman-core:0.2 
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman/
              name: mailman-core-volume
          env:
            - name: DATABASE_URL
              value: postgres://mailman:mailmanpass@mailman-database-0.mail-suit-service.mail.svc.cluster.local/mailmandb
            - name: DATABASE_TYPE
              value: postgres
            - name: DATABASE_CLASS
              value: mailman.database.postgresql.PostgreSQLDatabase
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailsecret
                  key: HYPERKITTY_API_KEY
            - name: HYPERKITTY_URL
              value: http://mailman-web-service.mail.svc.cluster.local:8000/hyperkitty
            - name: SMTP_HOST
              value: mailman-exim4-service.mail.svc.cluster.local
      volumes:
        - name: mailman-core-volume
          persistentVolumeClaim:
            claimName: config-vol
